server/healthaggregation/healthaggregation/data/models.py
# -*- coding: utf-8 -*-
"""Data models."""
import datetime as dt

from sqlalchemy import ForeignKey, func, event

from healthaggregation.database import PkModel, Model, Column, db, reference_col, relationship


class ParticipatingDevice(Model):
    __tablename__ = "participating_devices"

    request_id = Column(ForeignKey("data_requests.id"), primary_key=True)
    id = Column(db.Integer, primary_key=True)
    public_key = Column(db.String, nullable=False, primary_key=False)
    diffie_hellmann_public_component = Column(db.String, nullable=False)

    def __init__(self, **kwargs):
        """Create instance."""
        super().__init__(**kwargs)

    def __str__(self):
        """Represent instance as a string."""
        return f"<ParticipatingDevice({self.request_id!r}:{self.public_key!r})>"

    def __repr__(self):
        """Represent instance as a unique string."""
        return f"<ParticipatingDevice({self.request_id!r}:{self.public_key!r})>"

    def json(self):
        return {"request_id": self.request_id,
                "public_key": self.public_key,
                "diffie_hellmann_public_component": self.diffie_hellmann_public_component,
                "id": self.id
                }


@event.listens_for(ParticipatingDevice, 'before_insert')
def calculate_device_id(mapper, connect, target):
    existing_participating_device = ParticipatingDevice \
        .query \
        .filter_by(request_id=target.request_id) \
        .group_by(ParticipatingDevice.request_id) \
        .having(func.max(ParticipatingDevice.id)) \
        .first()
    target.id = existing_participating_device.id + 1 if existing_participating_device else 1


class DataRequests(PkModel):
    __tablename__ = "data_requests"

    requesting_user = reference_col("users", nullable=False)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    requested_url = Column(db.String(256), nullable=False)
    expected_dimensionality = Column(db.Integer, nullable=False)

    responses = relationship("DataResponse", cascade="all,delete", backref="request_obj")
    participating_devices = relationship("ParticipatingDevice", cascade="all,delete", backref="request_obj")
    participating_device_shares = relationship("ParticipatingDeviceSecretShares",
                                               cascade="all,delete",
                                               backref="request_obj")
    dropped_client_shares = relationship("DroppedClientSecretShares",
                                         cascade="all,delete",
                                         backref="request_obj")

    def __init__(self, **kwargs):
        """Create instance."""
        super().__init__(**kwargs)


class DataResponse(PkModel):
    __tablename__ = "data_responses"

    request = reference_col("data_requests", nullable=False)
    data = Column(db.PickleType, nullable=False)

    def __init__(self, **kwargs):
        """Create instance."""
        super().__init__(**kwargs)


class ParticipatingDeviceSecretShares(Model):
    __tablename__ = "participating_device_secret_shares"

    request_id = Column(ForeignKey("data_requests.id"), primary_key=True)
    encrypted_for_device = Column(db.Integer, nullable=False, primary_key=True)
    secret_of_dropped_device = Column(db.Integer, nullable=False, primary_key=True)
    secret_with_device = Column(db.Integer, nullable=False, primary_key=True)
    share_id = Column(db.Integer, nullable=False, primary_key=False)
    encrypted_share = Column(db.PickleType, nullable=False)

    def __init__(self, **kwargs):
        """Create instance."""
        super().__init__(**kwargs)

    def json(self):
        return {"request_id": self.request_id,
                "encrypted_for_device": self.encrypted_for_device,
                "secret_of_dropped_device": self.secret_of_dropped_device,
                "secret_with_device": self.secret_with_device,
                "share_id": self.share_id,
                "encrypted_share": self.encrypted_share
                }


class DroppedClientSecretShares(Model):
    __tablename__ = "dropped_client_secret_shares"

    request_id = Column(ForeignKey("data_requests.id"), primary_key=True)
    secret_of_dropped_device = Column(db.Integer, nullable=False, primary_key=True)
    secret_with_device = Column(db.Integer, nullable=False, primary_key=True)
    share_id = Column(db.Integer, nullable=False, primary_key=True)
    decrypted_share = Column(db.PickleType, nullable=False)

    def __init__(self, **kwargs):
        """Create instance."""
        super().__init__(**kwargs)

server/healthaggregation/healthaggregation/data/forms.py
from flask_wtf import FlaskForm

from wtforms import IntegerField, DateField, StringField
from wtforms.validators import DataRequired, Length, NumberRange

from healthaggregation.user.models import User

import re


class CreateRequestForm(FlaskForm):
    """Create request form."""

    requesting_user = IntegerField("Requesting User", validators=[DataRequired()])
    created_at = DateField("Date", validators=[DataRequired()])
    requested_url = StringField("Requested URL", validators=[DataRequired(), Length(min=0, max=256)])
    expected_dimensionality = IntegerField("Expected Dimensionality",
                                           validators=[DataRequired(), NumberRange(min=0)])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(CreateRequestForm, self).__init__(*args, **kwargs)

    def validate(self, extra_validators=None):
        """Validate the form."""
        initial_validation = super(CreateRequestForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(id=self.requesting_user.data).first()
        if not user:
            self.requesting_user.errors.append("This user doesn't exist")
            return False
        return True

server/healthaggregation/healthaggregation/data/__init__.py
# -*- coding: utf-8 -*-
"""The data module."""
from . import views  # noqa

server/healthaggregation/healthaggregation/data/views.py
# -*- coding: utf-8 -*-
"""Data views."""
import datetime
import json

from flask import Blueprint, request, Response, url_for, redirect, render_template
from flask_login import login_required, current_user

from healthaggregation.cloudmessaging.firebase_cloud_messaging import send_new_data_request
from healthaggregation.data.forms import CreateRequestForm
from healthaggregation.data.lib import get_responses
from healthaggregation.data.models import DataRequests, ParticipatingDevice, DroppedClientSecretShares
from healthaggregation.utils import flash_errors

blueprint = Blueprint("data", __name__, url_prefix="/data", static_folder="../static")


@blueprint.route("/request/responses", methods=["GET"])
@login_required
def responses():
    if request.args is None or "id" not in request.args:
        return Response({"400 Bad Request"}, status=400)
    data_request = DataRequests.query.filter_by(id=request.args.get("id")).first()
    if data_request is None:
        flash_errors({"id": "This request does not exist"})
        return redirect(url_for("public.home"))
    avg, \
    sum, \
    first_round_participants, \
    second_round_participants, \
    third_round_participants, \
    print_reconstruction_warning = get_responses(data_request)
    return render_template("data/responses.html",
                           request=data_request,
                           avg=avg,
                           sum=sum,
                           first_round_participants=first_round_participants,
                           second_round_participants=second_round_participants,
                           third_round_participants=third_round_participants,
                           print_reconstruction_warning=print_reconstruction_warning)


@blueprint.route("/request/create", methods=["GET", "POST"])
@login_required
def create_request_data():
    """Create a new data request."""
    form = CreateRequestForm(obj=request.form, data={"requesting_user": current_user.id,
                                                                           "created_at": datetime.datetime.utcnow()})
    if request.form is not None and ("requesting_user" in request.form or "created_at" in request.form):
        return Response(json.dumps({"error": "You can't overwrite the requesting user or the timestamp"}), status=400)
    if form.validate_on_submit():
        req = DataRequests.create(
            requesting_user=form.requesting_user.data,
            created_at=datetime.datetime.now(),
            requested_url=form.requested_url.data,
            expected_dimensionality=form.expected_dimensionality.data
        )
        send_new_data_request(req)
        return redirect(url_for("public.home"))
    else:
        flash_errors(form)
        return render_template("data/create_request.html", form=form)


@blueprint.route("/request/delete", methods=["GET"])
@login_required
def delete_data_request():
    """Delete a data request."""
    if request.args is None or "id" not in request.args:
        return Response({"400 Bad Request"}, status=400)
    if not current_user.is_admin:
        return Response("403 Forbidden", status=403)
    data_request = DataRequests.query.filter_by(id=request.args.get("id")).first()
    if data_request is None:
        return Response("404 Data Request Not Found", status=404)
    data_request.delete()
    return redirect(url_for("public.home"))

server/healthaggregation/healthaggregation/templates/data/create_request.html
{% extends "layout.html" %}
{% block content %}
<div class="container-narrow">
  <h1 class="mt-5">Create new data request</h1>
    <br/>
    <form id="registerForm" class="form form-register" method="POST" action="" role="form">
           {{ form.csrf_token }}
            <div class="form-group">
                {{form.requested_url.label}}
                {{form.requested_url(placeholder="URL to request", class_="form-control")}}
            </div>
            <div class="form-group">
                {{form.expected_dimensionality.label}}
                {{form.expected_dimensionality(placeholder="Dimensionality", class_="form-control")}}
            </div>
            <p><input class="btn btn-primary" type="submit" value="Create"></p>
    </form>
</div>
{% endblock %}

server/healthaggregation/healthaggregation/templates/data/dashboard.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <h1 class="mt-5">Dashboard</h1>

        <div class="row mt-5">
            <div class="col">
                <h2>Data Requests</h2>
            </div>
            {%  if current_user and current_user.is_authenticated and current_user.is_admin %}
              <div class="col align-self-end">
                <a class="btn btn-primary float-end" role="button" href="{{ url_for('data.create_request_data') }}">Create new request</a>
              </div>
            {% endif %}
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Requested URL</th>
                    <th scope="col">Requesting User</th>
                    <th scope="col">Created at</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for request in requests %}
                <tr>
                    <th scope="row">{{request.id}}</th>
                    <td>{{request.requested_url}}</td>
                    <td>{{request.user.username}}</td>
                    <td>{{request.created_at}}</td>
                    <td>
                        {%  if current_user and current_user.is_authenticated %}
                          <a class="btn btn-secondary" role="button" href="{{ url_for('data.responses') }}?id={{request.id}}"><i class="fa fa-search"></i></a>
                        {% endif %}
                    </td>
                    <td>
                        {%  if current_user and current_user.is_authenticated and current_user.is_admin %}
                          <a class="btn btn-danger" role="button" href="{{ url_for('data.delete_data_request') }}?id={{request.id}}"><i class="fa fa-trash"></i></a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock %}

server/healthaggregation/healthaggregation/templates/data/responses.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <h1 class="mt-5">Responses for Request {{ request.id }}</h1>

        <div class="row mt-5">
            <h4>Requested URL: {{ request.requested_url }}</h4>
            <h4>Requested At: {{ request.created_at }}</h4>
            <h4>Requested By: {{ request.user.username }}</h4>
            <h4>Dimensionality: {{ request.expected_dimensionality }}</h4>
            <h4></h4>
            <h4>Average: {{ avg }}</h4>
            <h4>Sum: {{ sum }}</h4>
            <h4></h4>
            <h4>First Round Participants: {{ first_round_participants }}</h4>
            <h4>Response Round Participants: {{ second_round_participants }}</h4>
            <h4>Recovery Round Participants: {{ third_round_participants }}</h4>
            <h4></h4>
            {%  if print_reconstruction_warning %}
                <h4 style="color: red">WARNING: Not enough clients have participated in the recovery round. The correct aggregates could not be reconstructed</h4>
            {% endif %}
            {%  if first_round_participants > 3 %}
                <h4 style="color: red">WARNING: Too few clients have participated. The secure aggregation protocol requires at least 3 participants in the first round</h4>
            {% endif %}
        </div>
        <div class="row mt-5">
            <div class="col align-self-end">
                <a class="btn btn-secondary float-end" role="button" href="{{ url_for('public.home') }}">Back</a>
            </div>
        </div>

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Data</th>
                </tr>
            </thead>
            <tbody>
                {% for response in request.responses %}
                <tr>
                    <th scope="row">{{response.id}}</th>
                    <td>{{response.data}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock %}