server/healthaggregation/healthaggregation/user/models.py
# -*- coding: utf-8 -*-
"""User models."""
import datetime as dt

from flask_login import UserMixin
from sqlalchemy.ext.hybrid import hybrid_property

from healthaggregation.database import Column, PkModel, db, reference_col, relationship
from healthaggregation.extensions import bcrypt


class Role(PkModel):
    """A role for a user."""

    __tablename__ = "roles"
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = reference_col("users", nullable=True)
    user = relationship("User", backref="roles")

    def __init__(self, name, **kwargs):
        """Create instance."""
        super().__init__(name=name, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return f"<Role({self.name})>"


class User(UserMixin, PkModel):
    """A user of the app."""

    __tablename__ = "users"
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    _password = Column("password", db.LargeBinary(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)

    responses = relationship("DataRequests", backref="user")

    @hybrid_property
    def password(self):
        """Hashed password."""
        return self._password

    @password.setter
    def password(self, value):
        """Set password."""
        self._password = bcrypt.generate_password_hash(value)

    def check_password(self, value):
        """Check password."""
        return bcrypt.check_password_hash(self._password, value)

    @property
    def full_name(self):
        """Full user name."""
        return f"{self.first_name} {self.last_name}"

    @property
    def json(self):
        return {"username": self.username, "email": self.email, "created_at": self.created_at,
                "first_name": self.first_name, "last_name": self.last_name, "active": self.active,
                "is_admin": self.is_admin
                }

    def __repr__(self):
        """Represent instance as a unique string."""
        return f"<User({self.username!r})>"

server/healthaggregation/healthaggregation/user/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length, Optional

from .models import User


class CreateForm(FlaskForm):
    """Create form."""

    username = StringField(
        "Username", validators=[DataRequired(), Length(min=3, max=25)]
    )
    email = StringField(
        "Email", validators=[DataRequired(), Email(), Length(min=6, max=40)]
    )
    first_name = StringField(
        "First Name", validators=[Optional(), Length(min=1, max=30)]
    )
    last_name = StringField(
        "Last Name", validators=[Optional(), Length(min=1, max=30)]
    )
    password = PasswordField(
        "Password", validators=[DataRequired(), Length(min=6, max=40)]
    )
    confirm = PasswordField(
        "Verify password",
        [DataRequired(), EqualTo("password", message="Passwords must match")],
    )

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(CreateForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self, extra_validators=None):
        """Validate the form."""
        initial_validation = super(CreateForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Username already registered")
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        return True

server/healthaggregation/healthaggregation/user/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import views  # noqa

server/healthaggregation/healthaggregation/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template, flash, redirect, url_for, request, Response
from flask_login import login_required, current_user

from healthaggregation.user.forms import CreateForm
from healthaggregation.user.models import User
from healthaggregation.utils import flash_errors

blueprint = Blueprint("user", __name__, url_prefix="/users", static_folder="../static")


@blueprint.route("/")
@login_required
def members():
    """List members."""
    users = User.query
    return render_template("users/members.html", users=users)


@blueprint.route("/create", methods=["GET", "POST"])
@login_required
def create():
    """Register new user."""
    if not current_user.is_admin:
        return Response("403 Forbidden", status=403)
    form = CreateForm(request.form)
    if form.validate_on_submit():
        User.create(
            username=form.username.data,
            email=form.email.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            password=form.password.data,
            active=True,
        )
        return redirect(url_for("user.members"))
    else:
        flash_errors(form)
    return render_template("users/create.html", form=form)


@blueprint.route("/makeadmin", methods=["GET", "POST"])
@login_required
def makeadmin():
    """Promote a user to admin"""
    if request.args is None or "id" not in request.args:
        return Response({"400 Bad Request"}, status=400)
    if not current_user.is_admin:
        return Response("403 Forbidden", status=403)
    user = User.query.filter_by(id=request.args.get("id")).first()
    if user is None:
        return Response("404 Account Not Found", status=404)
    user.is_admin = True
    user.update()
    return redirect(url_for("user.members"))


@blueprint.route("/delete", methods=["GET", "POST"])
@login_required
def delete():
    """Delete a user."""
    if request.args is None or "id" not in request.args:
        return Response({"400 Bad Request"}, status=400)
    if not current_user.is_admin:
        return Response("403 Forbidden", status=403)
    user = User.query.filter_by(id=request.args.get("id")).first()
    if user is None:
        return Response("404 Account Not Found", status=404)
    if user.id == current_user.id:
        flash("You can't delete your own account", "info")
        return redirect(url_for("user.members"))
    user.delete()
    return redirect(url_for("user.members"))

server/healthaggregation/healthaggregation/templates/users/create.html
{% extends "layout.html" %}
{% block content %}
<div class="container-narrow">
  <h1 class="mt-5">Register</h1>
    <br/>
    <form id="registerForm" class="form form-register" method="POST" action="" role="form">
           {{ form.csrf_token }}
            <div class="form-group">
                {{form.username.label}}
                {{form.username(placeholder="Username", class_="form-control")}}
            </div>
            <div class="form-group">
                {{form.email.label}}
                {{form.email(placeholder="Email", class_="form-control")}}
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
                {{form.first_name.label}}
                {{form.first_name(placeholder="First Name", class_="form-control")}}
            </div>
            <div class="form-group">
                {{form.last_name.label}}
                {{form.last_name(placeholder="Last Name", class_="form-control")}}
            </div>
            <div class="form-group">
                {{form.password.label}}
                {{form.password(placeholder="Password", class_="form-control")}}
            </div>
            <div class="form-group">
                {{form.confirm.label}}
                {{form.confirm(placeholder="Password (again)", class_="form-control")}}
            </div>
            <p><input class="btn btn-primary" type="submit" value="Create"></p>
    </form>
</div>
{% endblock %}

server/healthaggregation/healthaggregation/templates/users/members.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <h1 class="mt-5">User Management</h1>

     <h2 class="mt-5">Statistics</h2>
    <ul>
        <li><em># of users</em>: {{users.paginate().total}}</li>
    </ul>

    <div class="row mt-5">
        <div class="col">
            <h2>Overview</h2>
        </div>
        {%  if current_user and current_user.is_authenticated and current_user.is_admin %}
          <div class="col align-self-end">
            <a class="btn btn-primary float-end" role="button" href="{{ url_for('user.create') }}">Create user</a>
          </div>
        {% endif %}
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Username</th>
                <th scope="col">Email</th>
                <th scope="col">Created at</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Active</th>
                <th scope="col">Is admin</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <th scope="row">{{user.id}}</th>
                <td>{{user.username}}</td>
                <td>{{user.email}}</td>
                <td>{{user.created_at}}</td>
                <td>{{user.first_name}}</td>
                <td>{{user.last_name}}</td>
                <td>{{user.active}}</td>
                <td>{{user.is_admin}}</td>
                <td>
                    {%  if current_user and current_user.is_authenticated and current_user.is_admin %}
                      <a class="btn btn-danger" role="button" href="{{ url_for('user.delete') }}?id={{user.id}}" title="Delete user"><i class="fa fa-trash"></i></a>
                    {% endif %}
                </td>
                <td>
                    {%  if current_user and current_user.is_authenticated and current_user.is_admin and not user.is_admin%}
                      <a class="btn btn-warning" role="button" href="{{ url_for('user.makeadmin') }}?id={{user.id}}" title="Make admin"><i class="fa fa-crown"></i></a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    </div>
{% endblock %}